export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NOT_FOUND_IMAGE =
  "https://pvljogumgjnzfsbjpyke.supabase.co/storage/v1/object/sign/supermarket/not_found.webp?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJzdXBlcm1hcmtldC9ub3RfZm91bmQud2VicCIsInRyYW5zZm9ybWF0aW9ucyI6IiIsImlhdCI6MTY3MDY5NDYzOCwiZXhwIjoxOTg2MDU0NjM4fQ.7XQ3ezS73jaMVQWzJXZslVp-zxX4XOdub72e5avQ3Cg&t=2022-12-10T17%3A50%3A39.411Z";
